### ISSUE TITLE
Consider changing how we create example data.

### ISSUE THREAD

**Issue by jsocolar** [jsocolar/flocker#23]
Currently, we have a function `example_flocker_data` that serves no purpose other than to produce one of two example datasets (one with visit-specific covariates, one without) for use in further examples or testing.

Is this clunky compared to just including the data as an Rdata object, or brilliant, since the function + seed can regenerate the (relatively large) dataset in a very lightweight manner?

**Comment by SimonCMills** [comment]
I also quite like that by providing it as a function the model the data are simulated from is transparent, wheras this would be opaque if it was provided as data object. I think the function itself can be tidied up somewhat, but otherwise I think this arrangement is fine.

**Comment by SimonCMills** [comment]
I took a look at it and had a go at rewriting it (submitted as pull request): I *think* this code is more transparent, but you may disagree. It's much easier this way to allow covariates to be structured by e.g. point, species, point:visit combination (which visit-level covariates typically will be): sc1 and sc2 are now structured by point rather than by closure unit, and vc1 and vc2 are now structured by point:visit combination rather than by point:visit:species combination, so more reflective of the sort of data structures we actually get in reality.

**Comment by jsocolar** [comment]
closing this now with merge of your pr
