### ISSUE TITLE
Standardize names (site, point, unit, etc) across functions and doc

### ISSUE THREAD

**Issue by jsocolar** [jsocolar/flocker#31]
@SimonCMills We should use consistent terminology across our code and our doc.  Right now, for example, we have "(visit-)constant covariates" in some places but "unit covariates" in other places.  

I propose:

- We continue to use "(closure-)unit" to refer to sites, species-sites, etc.
- Detection models are either "visit-constant" or "visit-varying"

Then we have two options for what to call covariates.

OPTION 1:  Covariates are either "visit-constant" or "visit-varying". 

- Advantages: This emphasizes that what matters is not whether the covariate is conceptually a property of a closure-unit or a visit, but rather whether or not a covariate is constant across visits in the data.  For example, observer is conceptually a property of visits, but in a dataset where every unit is visited by only one observer, the covariate is still visit-constant.
- Disadvantages: Consider `names(example_flocker_data())`, which currently is `"obs"  "unit_covs"  "visit_covs"`.  Either we'd need to change `unit_covs` to `constant_covs`, which I think is confusing since the covariantes aren't constant (of course) but rather are *visit-constant*, or we'd need to use something quite cumbersome like "visit_constant_covs"  and "visit_varying_covs"`.

OPTION 2: Covariates are either "unit" or "visit".  
- The +/- is the inverse of the above.  
- Additional minus is that "unit covs" would require users to read documentation to figure out what the heck we mean.
- And additional minus is that it's less obvious than option 1 that "unit covariates" can just as well be properties of groups of units (like species traits or site characteristics in a multispecies model).  So "unit covariates" don't always vary at the level of "units".

**Comment by SimonCMills** [comment]
@jsocolar I think closure-unit works well (perhaps a bit cumbersome, but I can't think of anything better that is sufficiently general). 

Of the two options, I prefer option 2. Yes, people will have to read the documentation, but all it requires is being very clear that it's a catch-all term that refers to "site" in a single-species model, and "site:species" in a multispecies model. The only other question is whether `visit_covs` is sufficiently general, given that you might just as well have spatial replication rather than temporal? Would `rep_covs` or similar work better?

**Comment by jsocolar** [comment]
Closed via https://github.com/jsocolar/flocker/commit/8cdde6f2028198698e7e26232aefc2ba0b012177
